name: LeetCode Auto Sync

on:
  schedule:
    # 6:00 AM India time every day (00:30 UTC)
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Sync LeetCode solutions
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRFTOKEN: ${{ secrets.LEETCODE_CSRFTOKEN }}
          LEETCODE_USERNAME: mynameischethan
        run: python sync_leetcode.py

      - name: Commit new solutions
        run: |
          git config user.name "LeetCode Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          
          if git diff --cached --quiet; then
            echo "No new solutions."
          else
            git commit -m "Auto-sync LeetCode solutions"
            git push
          fi
